services:
  server:
    image: stashapp/stash:latest
    container_name: salesawagner-stashapp_server_1
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - ${APP_DATA_DIR}/data/config:/root/.stash
      - ${APP_DATA_DIR}/data/stash:/data
      - ${APP_DATA_DIR}/data/generated:/generated
      - ${APP_DATA_DIR}/data/metadata:/metadata
      - ${APP_DATA_DIR}/data/cache:/cache
    ports:
      - ${APP_PORT}:9999
    restart: on-failure
