services:
  clonarr:
    image: ghcr.io/prophetse7en/clonarr:latest
    container_name: clonarr
    restart: unless-stopped
    ports:
      - "6060:6060"
    environment:
      - TZ=America/Sao_Paulo
      - PUID=99
      - PGID=100
    volumes:
      - ./clonarr-config:/config